OMS/Models/MadicalStore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OMS.Models
{
    public class MadicalStore
    {
        public int MadicalStoreID { get; set; }
        public string Name { get; set; }

        [Required]
        [Display(Name = "Mobile No")]
        public string MobileNo { get; set; }

        [Required]
        [Display(Name = "Store Name")]

        public string StoreName { get; set; }
        [Required]
        [Display(Name = "Store License")]
        public string StoreLicense { get; set; }
        [Required]
        [Display(Name = "City")]
        public string City { get; set; }
        [Required]
        [Display(Name = "LandLine ")]
        public string LandLine { get; set; }
        [Required]
        [Display(Name = "Store Address ")]
        public string StoreAddress { get; set; }
        public string userid { get; set; }
        public string StoreImage { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}

OMS/Controllers/MadicalStoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using OMS.DAL;
using OMS.Models;

namespace OMS.Controllers
{
    public class MadicalStoresController : Controller
    {
        private MedicalContext db = new MedicalContext();
        [Authorize(Roles = "confirm")]
        // GET: MadicalStores
        public ActionResult Index()
        {
            string s = User.Identity.GetUserName();
            return View(db.MadicalStores.Where(x => x.userid == s).ToList());
        }



        //Serch and Result 

        public ActionResult bycity(string area)
        {
            var c = db.MadicalStores.DistinctBy(x=>x.City).ToList();
            
            if (!string.IsNullOrEmpty(area))
            {
                var y = db.MadicalStores.Where(a => a.City == area).ToList();


                var x = new List<MadicalStore>();
                foreach (var ob in y)
                {
                    x.Add(ob);
                }
                TempData["re"] = x;
                return RedirectToAction("result", ViewData["re"]);
            }
            else
           
                return
                   View(c);
           
               


        }

        public ActionResult result(IList<MadicalStore> x)
        {

            return View(x);
        }























        [Authorize(Roles = "confirm")]
        // GET: MadicalStores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MadicalStore madicalStore = db.MadicalStores.Find(id);
            if (madicalStore == null)
            {
                return HttpNotFound();
            }
            return View(madicalStore);
        }
        [Authorize(Roles = "confirm")]
        // GET: MadicalStores/Create
        public ActionResult Create()
        {
            if (User.IsInRole("confirm"))
            {
                MadicalStore m = new MadicalStore();
                m.userid = User.Identity.GetUserName();
                return View(m);
            }
            return RedirectToAction("Blocked");
        }
        [Authorize]
        public ActionResult Blocked()
        {
            return View();
        }
        [Authorize(Roles = "confirm")]
        // POST: MadicalStores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MadicalStoreID,Name,MobileNo,StoreName,StoreLicense,City,LandLine,StoreAddress,userid")] MadicalStore madicalStore,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                madicalStore.StoreImage = file.FileName;
                SaveFileToDisk(file);
                db.MadicalStores.Add(madicalStore);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(madicalStore);
        }
        [Authorize(Roles = "confirm")]
        // GET: MadicalStores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MadicalStore madicalStore = db.MadicalStores.Find(id);
            if (madicalStore == null)
            {
                return HttpNotFound();
            }
            return View(madicalStore);
        }
        [Authorize(Roles = "confirm")]
        // POST: MadicalStores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MadicalStoreID,Name,MobileNo,StoreName,StoreLicense,City,LandLine,StoreAddress,userid")] MadicalStore madicalStore, HttpPostedFileBase file, string img)
        {
            if (ModelState.IsValid)
            {
                db.Entry(madicalStore).State = EntityState.Modified;
                if (file != null)
                {
                    madicalStore.StoreImage = file.FileName;
                    SaveFileToDisk(file);
                    db.SaveChanges();
                }
                else
                {
                    madicalStore.StoreImage = img;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            return View(madicalStore);
        }
        [Authorize(Roles = "confirm")]
        // GET: MadicalStores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MadicalStore madicalStore = db.MadicalStores.Find(id);
            if (madicalStore == null)
            {
                return HttpNotFound();
            }
            return View(madicalStore);
        }
        [Authorize(Roles = "confirm")]
        // POST: MadicalStores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MadicalStore madicalStore = db.MadicalStores.Find(id);
            db.MadicalStores.Remove(madicalStore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void SaveFileToDisk(HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            img.Resize(img.Width, img.Height);

            img.Save(Constaants.ProductImagePath + file.FileName);

            img.Resize(100, img.Height);

            img.Save(Constaants.ProductThumbnailPath + file.FileName);



        }




    }

}

OMS/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OMS.DAL;
using OMS.Models;
using OMS.ViewModel;

namespace OMS.Controllers
{
    public class ProductsController : Controller
    {
        private MedicalContext db = new MedicalContext();
        [Authorize(Roles = "confirm")]
        // GET: Products
        public ActionResult Index()
        {
            //ProductStoreViewModel ps = new ProductStoreViewModel();
            string s = User.Identity.GetUserName();
            var products = db.Products.Where(x=>x.MadicalStore.userid==s).Include(p => p.MadicalStore);
            return View(products.ToList());
        }


        //Products list for visitors search




        public ActionResult PublicProductList(string MadicalStore, string Category, string search, string id)
        {
            var products = db.Products.Include(p => p.MadicalStore);
            if (!String.IsNullOrEmpty(MadicalStore))
            {
                products = products.Where(p => p.MadicalStore.Name == MadicalStore);
            }
            if (!String.IsNullOrEmpty(Category))
            {
                products = products.Where(p => p.Category == Category);
            }
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.ProducName.Contains(search) ||
                p.Producformula.Contains(search) ||
                p.Productweight.Contains(search) ||
                p.Description.Contains(search) ||
                p.Category.Contains(search) ||
                p.MadicalStore.Name.Contains(search) ||
                p.MadicalStore.City.Contains(search) ||
                p.MadicalStore.StoreAddress.Contains(search) ||
                p.MadicalStore.StoreName.Contains(search) ||
                p.Producformula.Contains(search));
            }
            if (!String.IsNullOrEmpty(id))
            {
                products = products.Where(p => p.MadicalStore.StoreLicense == id);
            }
            return View(products.ToList());
        }













        public ActionResult PublicPageStores()
        {
            
            var stores = db.MadicalStores;
            return View(stores.ToList());
        }
        public ActionResult PublicPageCategories()
        {

            var stores = db.Products;
            return View(stores.ToList());
        }



        public ActionResult PublicPage(String id)
        {
            var products = db.Products.Include(p => p.MadicalStore);
            if (id!=null)
            {
                products = products.Where(p => p.MadicalStore.StoreLicense == id);
            }
           
            return View(products.ToList());
        }















        //public ActionResult PublicPage(string MadicalStore, string Category, string search)
        //{
        //    var products = db.Products.Include(p => p.MadicalStore);
        //    if (!String.IsNullOrEmpty(MadicalStore))
        //    {
        //        products = products.Where(p => p.MadicalStore.Name == MadicalStore);
        //    }
        //    if (!String.IsNullOrEmpty(Category))
        //    {
        //        products = products.Where(p => p.Category == Category);
        //    }
        //    if (!String.IsNullOrEmpty(search))
        //    {
        //        products = products.Where(p => p.ProducName.Contains(search) ||
        //        p.Producformula.Contains(search) ||
        //        p.Productweight.Contains(search) ||
        //        p.Description.Contains(search) ||
        //        p.Category.Contains(search) ||
        //        p.MadicalStore.Name.Contains(search) ||
        //        p.MadicalStore.City.Contains(search) ||
        //        p.MadicalStore.StoreAddress.Contains(search) ||
        //        p.MadicalStore.StoreName.Contains(search) ||
        //        p.Producformula.Contains(search));
        //    }
        //    return View(products.ToList());
        //}

        [Authorize(Roles = "confirm")]
        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }
        [Authorize(Roles = "confirm")]
        // GET: Products/Create
        public ActionResult Create()
        {
            string s = User.Identity.GetUserName();

            var madicalStoress = db.MadicalStores.Where(x => x.userid == s).ToList();
            ViewBag.MadicalStoreID = new SelectList(madicalStoress, "MadicalStoreID", "StoreName");
            
            return View();
        }
        [Authorize(Roles = "confirm")]
        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProducName,Producformula,Productweight,Price,Description,Category,MadicalStoreID")] Products products,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                products.productImage = file.FileName;
                SaveFileToDisk(file);
                db.Products.Add(products);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            string s = User.Identity.GetUserName();
            ViewBag.MadicalStoreID = new SelectList(db.MadicalStores, "MadicalStoreID", "StoreName", products.MadicalStoreID);
            return View(products);
        }
        [Authorize(Roles = "confirm")]
        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            string s = User.Identity.GetUserName();
            ViewBag.MadicalStoreID = new SelectList(db.MadicalStores.Where(x=>x.userid==s), "MadicalStoreID", "StoreName", products.MadicalStoreID);
            return View(products);
        }
        [Authorize(Roles = "confirm")]
        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProducName,Producformula,Productweight,Price,Description,Category,MadicalStoreID")] Products products,HttpPostedFileBase file,string img)
        {
            if (ModelState.IsValid)
            {
                db.Entry(products).State = EntityState.Modified;
                if (file != null)
                {
                    products.productImage = file.FileName;
                    SaveFileToDisk(file);
                    db.SaveChanges();
                }
                else
                {
                    products.productImage = img;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            string s = User.Identity.GetUserName();
            ViewBag.MadicalStoreID = new SelectList(db.MadicalStores, "MadicalStoreID", "StoreName", products.MadicalStoreID);
            return View(products);
        }
        [Authorize(Roles = "confirm")]
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }
        [Authorize(Roles = "confirm")]
        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        private void SaveFileToDisk(HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            img.Resize(img.Width, img.Height);

            img.Save(Constaants.ProductImagePath + file.FileName);

            img.Resize(100, img.Height);

            img.Save(Constaants.ProductThumbnailPath + file.FileName);



        }


    }
}

OMS/Views/MadicalStores/Blocked.cshtml
@{
    ViewBag.Title = "Blocked";
    Layout = "~/Views/Shared/_newlayout.cshtml";
}

<h1>Blocked</h1>
<h2>Sorry you are blocked by admin please contect our technical team</h2>

OMS/Views/MadicalStores/Create.cshtml
@model OMS.Models.MadicalStore

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="SimpliQ Bootstrap 4 Admin Template">
    <meta name="author" content="Lukasz Holeczek">
    <meta name="keyword" content="SimpliQ Bootstrap 4 Admin Template">
    <!-- <link rel="shortcut icon" href="assets/ico/favicon.png"> -->
    <title>Register</title>
    <!-- Icons -->
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/simple-line-icons.css" rel="stylesheet">
    <!-- Main styles for this application -->
    <link href="~/Content/css/style.css" rel="stylesheet">
</head>
<body class="app flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mx-2">
                    <div class="card-block p-2">


                        @using (Html.BeginForm("Create", "MadicalStores", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>MadicalStore</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.StoreName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.StoreName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.StoreLicense, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.StoreLicense, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.StoreLicense, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.LandLine, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.LandLine, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.LandLine, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.StoreAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.StoreAddress, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.StoreAddress, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.userid, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.userid, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.userid, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.StoreImage, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <input type="file" name="file" value="file" />
                                        @Html.ValidationMessageFor(model => model.StoreImage, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- Bootstrap and necessary plugins -->
        <script src="~/Content/FingerprintJS/es6-shim.js"></script>
        <script src="~/Content/FingerprintJS/websdk.client.bundle.min.js"></script>
        <script src="~/Content/FingerprintJS/fingerprint.sdk.min.js"></script>
        <script src="~/Content/app.js"></script>
        <script src="~/Content/js/libs/jquery.min.js"></script>
        <script src="~/Content/js/libs/tether.min.js"></script>
        <script src="~/Content/js/libs/bootstrap.min.js"></script>

</body>
</html>
<div>
  
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OMS/Views/MadicalStores/Delete.cshtml
@model OMS.Models.MadicalStore
@{
    ViewBag.Title = "Delete";
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MadicalStore</h4>
    <hr />
    <dl class="dl-horizontal">
  

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreLicense)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreLicense)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LandLine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LandLine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userid)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OMS/Views/MadicalStores/Index.cshtml
@model IEnumerable<OMS.Models.MadicalStore>

@{
    ViewBag.Title = "Index";
 Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="card card-outline-success">
            <div class="card-header">
                <h2>Medical Store|<small>List</small></h2>
            </div>
            <div class="card-block">
                <p>
                    @Html.ActionLink("Create New", "Create", "MadicalStores")
                </p>
                <table class="table table-striped datatable">
                    <thead>
                        <tr>
                            <th>
                                Store Name
                            </th>
                            <th>
                                Address
                            </th>

                            <th>
                                Licence
                            </th>
                            <th>
                                Phone No
                            </th>
                            <th>
                                Picture
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StoreName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StoreAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StoreLicense)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LandLine)
                                </td>
                                <td>
                                    <img src="~/Content/ProductImg/@item.StoreImage" width="100" height="100" />
                                </td>

                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.MadicalStoreID }) |

                                    @Html.ActionLink("Delete", "Delete", new { id = item.MadicalStoreID })
                                </td>
                            </tr>
                           
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

OMS/Views/MadicalStores/bycity.cshtml
@model IEnumerable<OMS.Models.MadicalStore>

@{
    ViewBag.Title = "bycity";
    Layout = "~/Views/Shared/_myLayout.cshtml";
}

<div class="agileits-modal modal fade" id="myModal88" tabindex="-1" role="dialog" aria-labelledby="myModal88"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><i class="fa fa-map-marker" aria-hidden="true"></i> Location</h4>
            </div>
            <div class="modal-body modal-body-sub">
                <h5>Select Your Nearest Medical Store Location </h5>
                @using (Html.BeginForm("bycity", "MadicalStores"))
                {
                    <select class="form-control bfh-states" name="area" id="area" data-country="US" data-state="CA">
                       @foreach(var item in Model)
                       {
                           <option value="@item.City">@item.City</option>
                       }

                    </select>
                    <input type="submit" value="search" />
                }

            </div>
        </div>
    </div>
</div>
<script>
        $('#myModal88').modal('show');
</script>